config_version = 14

[bar]
order = [ "default" ]

    [bar.default]
    auto_hide = false
    background_opacity = 1.0
    border = "outline"
    border_width = 0.0
    capsule = false
    capsule_fill = "surface_variant"
    capsule_group = []
    capsule_opacity = 1.0
    capsule_padding = 6.0
    capsule_thickness = 0.75999999046325684
    center = [ "clock" ]
    concave_edge_corners = true
    contact_shadow = false
    enabled = true
    end = [
        "media",
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "control-center",
        "session"
    ]
    font_scale = 1.0
    font_weight = 500
    hover_highlight = true
    layer = "top"
    margin_edge = 0
    margin_ends = 100
    margin_opposite_edge = 0
    padding = 14
    panel_overlap = 1
    position = "top"
    radius = 12
    radius_bottom_left = 12
    radius_bottom_right = 12
    radius_top_left = 12
    radius_top_right = 12
    reserve_space = true
    scale = 1.0
    shadow = true
    show_on_workspace_switch = true
    smart_auto_hide = false
    start = [ "launcher", "wallpaper", "workspaces", "scale" ]
    thickness = 34
    widget_spacing = 6

        [bar.default.dead_zone]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-login-box@winit"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "HDMI-A-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 852.50018310546875
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 634.0
    cy = 1201.0
    output = "winit"
    placement_height = 1383.0
    placement_width = 1268.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[theme]
custom_palette = "Coral and Sea"
source = "custom"

[wallpaper.default]
path = "/home/me1sgr/Pictures/Wallpapers/6quksxf6b7u51.jpg"

[wallpaper.last]
path = "/home/me1sgr/Pictures/Wallpapers/6quksxf6b7u51.jpg"

[wallpaper.monitors.DP-1]
path = "/home/me1sgr/Pictures/Wallpapers/6quksxf6b7u51.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/me1sgr/Pictures/Wallpapers/6quksxf6b7u51.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/me1sgr/Pictures/Wallpapers/6quksxf6b7u51.jpg"

[widget.scale]
glyph = "aspect-ratio"
type = "custom_button"

    [widget.scale.actions]
    left = "exec /home/me1sgr/.config/niri/scripts/scale-switcher.sh"
[shell]
app_icon_colorize = true
avatar_path = ""
button_borders = true
card_borders = true
clipboard_auto_paste = "auto"
clipboard_confirm_clear_history = true
clipboard_enabled = true
clipboard_history_max_entries = 100
clipboard_image_action_command = ""
clipboard_keep_from_closed_apps = true
corner_radius_scale = 1.0
date_format = "%A, %x"
disable_mipmaps = false
external_ip_enabled = false
font_family = "sans-serif"
input_borders = true
launch_apps_as_systemd_services = false
launch_apps_custom_command = ""
niri_overview_type_to_launch_enabled = false
offline_mode = false
password_style = "default"
polkit_agent = true
popup_borders = true
popup_shadows = true
screen_time_enabled = false
settings_show_advanced = true
settings_window_translucent = false
setup_wizard_enabled = true
shared_gl_context = true
show_location = true
telemetry_enabled = false
time_format = "{:%H:%M}"

    [shell.animation]
    enabled = true
    speed = 1.0

    [shell.greeter_sync]
    auto_sync = false

    [shell.keyboard_layout]

    [shell.launcher]
    app_grid = false
    auto_paste = "auto"
    categories = true
    compact = false
    fetch_exchange_rates = true
    pinned = []
    provider_prefix = "/"
    show_app_actions = false
    show_app_origin_indicator = true
    show_icons = true
    sort_by_usage = true

        [shell.launcher.dmenu]

    [shell.mpris]
    blacklist = []

    [shell.panel]
    borders = true
    clipboard_placement = "floating"
    clipboard_position = "center"
    control_center_placement = "attached"
    control_center_position = "auto"
    floating_layer = "overlay"
    floating_offset = 8
    launcher_placement = "floating"
    launcher_position = "center"
    list_item_background = false
    open_near_click_clipboard = false
    open_near_click_control_center = false
    open_near_click_launcher = false
    open_near_click_session = false
    open_near_click_wallpaper = false
    polkit_placement = "floating"
    polkit_position = "center"
    session_placement = "attached"
    session_position = "auto"
    shadow = true
    transparency_mode = "solid"
    wallpaper_placement = "attached"
    wallpaper_position = "auto"

    [shell.privacy]
    cam_filter_regex = ""
    mic_filter_regex = ""
    screen_filter_regex = ""

    [shell.screen_corners]
    enabled = false
    size = 32

    [shell.screenshot]
    confirm_region = false
    copy_to_clipboard = true
    directory = ""
    filename_pattern = ""
    freeze_screen = true
    pipe_command = ""
    pipe_to_command = false
    remember_last_region = false
    save_to_file = true
    show_cursor = false

    [shell.session]
    grid = false
    grid_columns = 3
    show_shortcuts = true

        [shell.session.power]

        [[shell.session.actions]]
        action = "lock"
        command = ""
        countdown_seconds = 0.0
        enabled = true
        glyph = ""
        label = ""
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        command = ""
        countdown_seconds = 0.0
        enabled = true
        glyph = ""
        label = ""
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        command = ""
        countdown_seconds = 0.0
        enabled = true
        glyph = ""
        label = ""
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        command = ""
        countdown_seconds = 0.0
        enabled = true
        glyph = ""
        label = ""
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        command = ""
        countdown_seconds = 0.0
        enabled = true
        glyph = ""
        label = ""
        shortcut = "5"
        variant = "destructive"

    [shell.shadow]
    alpha = 0.55000001192092898
    direction = "down"

    [shell.window_switcher]
    mru = false

[widget.bluetooth]
color = "#569cd6"
icon_color = "#569cd6"
type = "bluetooth"

[widget.network]
color = "#6a9955"
icon_color = "#6a9955"
type = "network"

[widget.volume]
color = "tertiary"
icon_color = "tertiary"
type = "volume"

[widget.brightness]
color = "#d7ba7d"
icon_color = "#d7ba7d"
type = "brightness"

[widget.battery]
color = "#4ec9b0"
icon_color = "#4ec9b0"
type = "battery"

[widget.notifications]
color = "primary"
icon_color = "primary"
type = "notifications"

[widget.clipboard]
color = "secondary"
icon_color = "secondary"
type = "clipboard"

[widget.session]
color = "error"
icon_color = "error"
type = "session"

[widget.control-center]
color = "#9cdcfe"
icon_color = "#9cdcfe"
type = "control-center"
