# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager  = dolphin
$applauncher  = wofi --show drun
$terminal     = kitty
$idlehandler  = hypridle
$lockcmd      = hyprlock
$capturing    = grim -g "$(slurp)" - | swappy -f -
