# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_THEME,Nordzy-archblue
envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_THEME,Nordzy-cursors
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24
