$font = FiraCode Nerd Font

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/mcgi5sr2/Videos/fish_tank_graphic.mp4
    blur_passes = 2
    blur_size = 4
    brightness = 0.7
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 80
    font_family = $font
    color = rgba(a0e8f0ff)

    position = 0, 100
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 22
    font_family = $font
    color = rgba(a0e8f0cc)

    position = 0, 20
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    inner_color = rgba(0d1a1fcc)

    outer_color = rgba(1793d1ff)
    check_color = rgba(1793d1ff)
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgba(a0e8f0ff)
    font_family = $font
    fade_on_empty = true
    rounding = 10

    placeholder_text = <i>Enter password...</i>
    fail_text = <b>$PAMFAIL</b>

    dots_spacing = 0.3
    dots_size = 0.3

    position = 0, -100
    halign = center
    valign = center
}
